name: Update test Version

on:
  release:
    types:
      - released
permissions:
  contents: read

jobs:
  update-shield:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Actualizar escudo de versión
      run: |
        version=$(awk -F"'" '/\$number_version/{print $2}' test_vers.php)
        echo "![Version](https://img.shields.io/badge/Version-$version-blue)" > README-shield.md


    - name: Actualizar README.md
      run: |
        mv README-shield.md README.md
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add README.md
        git commit -am "Actualizar escudo de versión [skip ci]"
        git push

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
